- connection: local
  hosts: localhost
  roles:
    - avinetworks.avisdk
    - avinetworks.avicontroller_vmware
  tasks:
  - include_vars: "library/controllerdeploy/defaults/defaults.yml"
  - include_tasks: library/controllerdeploy/tasks/controller_build.yml
    with_sequence:  count={{ deploy_controllers }}
    name: Deploy AviControllers VMWare
  - include_tasks: library/controllerdeploy/tasks/controller_init.yml
    name: Configure default settings on controller
  - set_stats:
      data:
        controller_mgmt: "{{ controller_mgmt_ip | ipaddr('address') | ipmath(loop_controller|int) }}"
    when: deploy_controllers > 1
