- connection: local
  hosts: localhost
  tasks:
  - set_stats:
      data:
        controller_mgmt: "{{ controller_mgmt_ip | ipaddr('address') }}"
        build_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+\\/+?', '\\1') }}"
        avi_api_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+-.*\\/+?', '\\1') }}"
  - set_stats:
      data:
        last_octet: "{{ data['controller_mgmt'].split('.')[3:4] | join('.')  }}"
