- connection: local
  hosts: localhost
  tasks:
  - set_stats:
      data:
        build_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+\\/+?', '\\1') }}"
        avi_api_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+-.*\\/+?', '\\1') }}"
        last_octet: "{{ controller_mgmt_ip.split('.')[3:4] | join('.') }}"
        loop_controller: 0
