- connection: local
  hosts: localhost'
  vars:
    octet_parse:  "{{ controller_mgmt_ip | ipaddr('address') }}"
  tasks:
  - set_stats:
      data:
        controller_mgmt: "{{ controller_mgmt_ip | ipaddr('address') }}"
        build_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+\\/+?', '\\1') }}"
        avi_api_version: "{{ ova_path | regex_replace('^.*build-([0-9].*)+-.*\\/+?', '\\1') }}"
        last_octet: "{{ octet_parse.split('.')[3:4] | join('.')  }}"
