- avi_useraccount:
    controller: "{{ controller_mgmt_ip | ipaddr('address') }}"
    username: "{{ lookup('env', 'AVI_USERNAME') }}"
    password: "{{ lookup('env', 'AVI_PASSWORD') }}"
    old_password: "{{ lookup('env', 'AVI_OLDPASSWORD') }}"
  name: "Change Default Password"
- avi_systemconfiguration:
    avi_credentials: "{{ avi_credentials }}"
    dns_configuration:
      server_list:
        - addr: 8.8.8.8
          type: V4
        - addr: 8.8.4.4
          type: V4
    ntp_configuration:
      ntp_server_list:
        - addr: 0.pool.ntp.org
          type: DNS
        - addr: 1.pool.ntp.org
          type: DNS
        - addr: 2.pool.ntp.org
          type: DNS
        - addr: 3.pool.ntp.org
          type: DNS
  name: Basic system configuration
- set_fact:
    avi_cluster_config: "{{ lookup('template', '../templates/cluster.j2')|from_yaml }}"
  when: deploy_controllers > 1
  name: Build Cluster Config
- avi_cluster: "{{ avi_cluster_config }}"
  when: deploy_controllers > 1
  name: Apply Cluster Config
- uri:
    validate_certs: False
    url: "{{ 'https://' + controller_mgmt_ip | ipaddr('address') | ipmath(loop_controller|int) + '/api/cluster/status'}}"
    method: GET
    status_code: 200
  register: status_code
  until: status_code.status == 200
  retries: 10
  delay: 60
  name: Verify Controller/Cluster is online
