---
- name: Avi SE | Docker | Services | Check
  include: checks/old_service.yml
  when: se_old_service

- name: Avi SE | Docker | Services | Check
  include: checks/new_service.yml
  when: se_new_service

- name: Avi SE | Docker | Services | Capture AVICOOKIE from docker run params
  set_fact:
    se_auth_token: "{{ se_existing_run_params|regex_replace('^.*AVICOOKIE=','')|regex_replace('--net.*','')|trim}}"
  when: se_existing_run_params is defined and not se_fresh_install
