---
- name: Avi SE | Docker | Services | Check for existing avise service
  stat: path=/usr/sbin/avise
  register: se_service_file
- name: Avi SE | Docker | Services | Read existing service's docker run configuration
  shell: cat /usr/sbin/avise | sed -n -e 's/^docker_run_params=//p' | tr -d '"'
  register: se_existing_run_params_raw
  changed_when: false
  when: se_service_file.stat.exists
- set_fact:
    existing_run_params: "{{ se_existing_run_params_raw.stdout }}"
    se_service_exists: "{{ se_service_file.stat.exists }}"
  when: se_service_file.stat.exists
