---
# These steps will allow a user to specify a private docker repository and login to that
# respository to pull docker images.
#
- block:
    - name: Avi SE | Docker | Log into the custom docker repository
      shell: "docker login -u {{ se_docker_repo_user }} -p {{ se_docker_repo_password}} {{ se_docker_repo }}"
      register: se_docker_repo_login
      when:
        - se_docker_repo_user != None
        - se_docker_repo_password != None
    - name: Avi SE | Docker | Load the image from custom docker repository
      shell: "docker pull {{ se_docker_repo }}/{{ se_image }}"
      register: se_load_docker_repo
      changed_when: "'Status: Image is up to date' not in se_load_docker_repo.stdout"
      notify: Avi SE | Services | Restart the avise service
  when: se_docker_match.stdout == "" or se_version == "latest"
