---
# Default docker image pull from the Docker Hub.

- name: Avi SE | Docker | Load the image from Docker Hub
  shell: "docker pull {{ se_image }}"
  register: se_load_docker_hub
  changed_when: "'Status: Image is up to date' not in se_load_docker_hub.stdout"
  notify: Avi SE | Services | Restart the avise service
  when: se_docker_match.stdout == "" or se_version == "latest"
