---
- block:
    - name: Avi SE | Requirements | init.d | Stop the avise_watcher service for fresh install
      service: name=avise_watcher enabled=no state=stopped
    - name: Avi SE | Requirements | init.d | Stop the avise service for fresh install
      service: name=avise enabled=no state=stopped
  when: ansible_service_mgr == 'init' or
        ( ansible_service_mgr != 'systemd' and se_old_service )

- name: Avi SE | Requirements | systemd | Stop the avise service for fresh install
  systemd: daemon_reload=yes name=avise enabled=no state=stopped
  when: ansible_service_mgr == 'systemd'

- name: Avi SE | Requirements | upstart | Stop the avise service for fresh install
  service: name=avise enabled=no state=stopped
  when: ansible_service_mgr == 'upstart' and se_new_service

- name: Avi SE | Requirements | Clean directories for fresh install
  file: path="{{ item }}" state=absent
  when: item != None
  with_items:
    - "{{ se_disk_path }}"
    - "{{ se_logs_disk_path }}"
